### ISSUE TITLE
can you leave your 

### ISSUE THREAD

**Issue by jayfen2016** [annuay/online-objective-examination-system#2]
直接中文吧，，，，
最近有做 这方面的东西，能留下你的QQ或者微信之类的联系方式吗，想跟你请教一下

**Comment by annuay** [comment]
I'm really sorry that I cannot understand Chinese, neither am I able to translate it online. It would be great if you could use English.

**Comment by jayfen2016** [comment]
nice to meet you.
i think you are a Chinese,but you are not.However it is very happy to contact with you.where are you from? I come from shanghai,maybe you heard.
now it is 22:14,so i need to go to the sleep.Next time ask your some questions about nodejs,thank you very much for answer me.


good night.


(maybe my english is very bad,please forgive me ,,,,,,,,) 




------------------ 原始邮件 ------------------
发件人: "annuay";<notifications@github.com>;
发送时间: 2016年4月3日(星期天) 晚上6:59
收件人: "annuay/online-objective-examination-system"<online-objective-examination-system@noreply.github.com>; 
抄送: "赵佳峰"<593312055@qq.com>; 
主题: Re: [annuay/online-objective-examination-system] can you leave your (#2)




I'm really sorry that I cannot understand Chinese, neither am I able to translate it online. It would be great if you could use English.

**Comment by jayfen2016** [comment]
hello.
when i run this program,i dont have any account.so i tried a accout that is 'admin/admin',but it appeard 
![Uploading 1738755346@chatroom_1459770606605_175.jpg…]()
![Uploading 1738755346@chatroom_1459770606605_175.jpg…]()
now i dont know how to do,,,,,,

**Comment by annuay** [comment]
Sorry that we missed this out in the readme, you need to create a mongodb database by the name examdb. Then create a collection called admin and add the following entry: {username: "admin", password: "password"}. Then you can log in.

**Comment by jayfen2016** [comment]
thank you very much,now i can login for your help.so it appears a new question:how to exam.When i logined as a student,i input exam_code,but there is nothing,i tried to add a cource,however it doesnt have anything.Can i see your database?i want to know what the construction of the database is.


by the way,where are you from?what application do you use to chat?Maybe we can make a friends~~~


------------------ 原始邮件 ------------------
发件人: "annuay";<notifications@github.com>;
发送时间: 2016年4月4日(星期一) 晚上8:38
收件人: "annuay/online-objective-examination-system"<online-objective-examination-system@noreply.github.com>; 
抄送: "赵佳峰"<593312055@qq.com>; 
主题: Re: [annuay/online-objective-examination-system] can you leave your (#2)




Sorry that we missed this out in the readme, you need to create a mongodb database by the name examdb. Then create a collection called admin and add the following entry: {username: "admin", password: "password"}. Then you can log in.
